@startuml
title rodi: both for those who like type hints and those who don't\n
start

if (Do you like type hints?) then (yes!)
  :you can use them;
  if (Do you want to disable aliases?) then (yes)
    :use <i>strict</i> mode to disable 
    resolution by param names;
  else (no)
    :you can use convention over 
    configuration, too (type hints take precedence);
  endif
else (no!)
  :you can use convention over configuration,
  by parameter names and aliases;
endif

stop

@enduml