@startuml classes

class ServiceCollection {
	+add_instance(instance, <color:royalBlue>optional</color> declared_type)
	..
	+add_singleton(base_type, concrete_type)
	+add_transient(base_type, concrete_type)
	+add_scoped(base_type, concrete_type)
	..
	+add_exact_singleton(concrete_type)
	+add_exact_transient(concrete_type)
	+add_exact_scoped(concrete_type)
	..
	+add_singleton_by_factory(factory, <color:royalBlue>optional</color> concrete_type)
	+add_transient_by_factory(factory, <color:royalBlue>optional</color> concrete_type)
	+add_scoped_by_factory(factory, <color:royalBlue>optional</color> concrete_type)
	..
	+register(base_type, concrete_type, lifestyle)
	+register_factory(factory, <color:royalBlue>optional</color> return_type)
	..
	+add_alias(name, desired_type)
	+set_alias(name, desired_type)
	+add_aliases(mapping)
	+set_aliases(mapping)
	..
	+ServiceProvider build_provider()
}

class ServiceProvider {
  +get(type)
	+get(type_name)
}

ServiceCollection -down-> ServiceProvider

@enduml